/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controladorConfiguracion;
import controlador.controladorDiurna;
import controlador.controladorPersona;
import controlador.controladorVespertina;
import modelo.Persona;

/**
 *
 * @author Milii2
 */
//
public class VentanaIngreso extends javax.swing.JFrame {
    /**
     * Creates new form VentanaIngreso
     *///
    public VentanaIngreso() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botondeingreso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        listaespecialidad = new javax.swing.JComboBox();
        listaprofesional = new javax.swing.JComboBox();
        listafacultad = new javax.swing.JComboBox();
        listacarrera = new javax.swing.JComboBox();
        cantidadatenciones = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JCalendar();
        listatipo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        barraprogreso = new javax.swing.JProgressBar();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        botondeingreso.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        botondeingreso.setText("Ingresar");
        botondeingreso.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel1.setText("Especialidad:");

        listaespecialidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaespecialidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>", "Medicina General", "Medicina Interna", "Odontología General", "Psiquiatría", "Nutriología", "Traumatología", "Psicología", "Enfermería", "Medicina en Hematología", "Kinesiología", "Cirugía", "Neurología" }));
        listaespecialidad.setEnabled(false);
        listaespecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaespecialidadActionPerformed(evt);
            }
        });

        listaprofesional.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaprofesional.setEnabled(false);

        listafacultad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listafacultad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>", "Administración y Economía", "Ciencias de la Construcción y Ordenamiento Territorial", "Ciencias Naturales, Matemática y del Medio Ambiente", "Humanidades y Tecnologías de la Comunicación Social", "Ingeniería" }));
        listafacultad.setEnabled(false);
        listafacultad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listafacultadItemStateChanged(evt);
            }
        });
        listafacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listafacultadActionPerformed(evt);
            }
        });

        listacarrera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listacarrera.setEnabled(false);

        cantidadatenciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cantidadatenciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cantidadatenciones.setEnabled(false);
        cantidadatenciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cantidadatencionesItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setText("Profesional:");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel3.setText("Facultad:");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setText("Carrera:");

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel5.setText("Número de Atenciones:");

        calendario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        calendario.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        calendario.setTodayButtonText("Fecha Actual");
        calendario.setTodayButtonVisible(true);
        calendario.setWeekOfYearVisible(false);

        listatipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listatipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>", "Diurno", "Vespertino" }));
        listatipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listatipoItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel6.setText("Tipo:");

        barraprogreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        barraprogreso.setStringPainted(true);

        volver.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/atras_opt (2).png"))); // NOI18N
        volver.setText("Volver");
        volver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel6)
                        .add(18, 18, 18)
                        .add(listatipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(158, 158, 158)
                        .add(volver))
                    .add(layout.createSequentialGroup()
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cantidadatenciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel4))
                        .add(30, 30, 30)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(listaprofesional, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(listaespecialidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(listafacultad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(listacarrera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(barraprogreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 291, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(botondeingreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(calendario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 417, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(jLabel6))
                    .add(layout.createSequentialGroup()
                        .add(19, 19, 19)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(volver)
                            .add(listatipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(listaespecialidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(listaprofesional, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(listafacultad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(listacarrera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cantidadatenciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .add(18, 18, 18)
                .add(calendario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(botondeingreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(barraprogreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    }//GEN-LAST:event_formWindowActivated

    private void listatipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listatipoItemStateChanged
        // TODO add your handling code here:
        String cadena = (String)listatipo.getSelectedItem();
        if (!"<Seleccione>".equals(cadena)){
            listaespecialidad.enable();
        }else{
            listaespecialidad.setSelectedIndex(0);
            listaespecialidad.disable();
            listaprofesional.disable();
            listafacultad.setSelectedIndex(0);
            listafacultad.disable();
            listacarrera.disable();
            cantidadatenciones.setSelectedIndex(0);
            cantidadatenciones.disable();
        }
    }//GEN-LAST:event_listatipoItemStateChanged

    private void listaespecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaespecialidadActionPerformed
        String cadena1 = (String)listaespecialidad.getSelectedItem();
        if (cadena1.equals("<Seleccione>")){
            listaprofesional.disable();
            listafacultad.setSelectedIndex(0);
            listafacultad.disable();
            listacarrera.disable();
            cantidadatenciones.setSelectedIndex(0);
            cantidadatenciones.disable();
        }else{
            listaprofesional.enable();
            listafacultad.enable();
        }
    }//GEN-LAST:event_listaespecialidadActionPerformed

        private void cantidadatencionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cantidadatencionesItemStateChanged
        // TODO add your handling code here:
            String cant = (String)cantidadatenciones.getSelectedItem();
            String tipo = (String)listatipo.getSelectedItem();
            String especialidad = (String)listaespecialidad.getSelectedItem();
            String facultad = (String)listafacultad.getSelectedItem();
            if(!"<Seleccione>".equals(cant) && !"<Seleccione>".equals(tipo) && !"<Seleccione>".equals(especialidad) && !"<Seleccione>".equals(facultad)){
                botondeingreso.setEnabled(true);
            }else{
                botondeingreso.setEnabled(false);
            }
    }//GEN-LAST:event_cantidadatencionesItemStateChanged

    private void listafacultadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listafacultadItemStateChanged
        // TODO add your handling code here:
        /*String esp = (String)listafacultad.getSelectedItem();
        if (esp != "<Seleccione>"){
            listacarrera.enable();
            cantidadatenciones.enable();
        }else{
            listacarrera.disable();
            cantidadatenciones.setSelectedIndex(0);
            cantidadatenciones.disable();
        }*/
    }//GEN-LAST:event_listafacultadItemStateChanged

    private void listafacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listafacultadActionPerformed
        // TODO add your handling code here:
        String esp = (String)listafacultad.getSelectedItem();
        if (!"<Seleccione>".equals(esp)){
            listacarrera.enable();
            cantidadatenciones.enable();
        }else{
            listacarrera.disable();
            cantidadatenciones.setSelectedIndex(0);
            cantidadatenciones.disable();
        }
    }//GEN-LAST:event_listafacultadActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       
       // VentanaPrincipal princ = new VentanaPrincipal();
       // Persona per = new Persona();
       // new controladorPersona(princ,per);
        
    }//GEN-LAST:event_formWindowClosed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventanaprincipal=new VentanaPrincipal();
        ventanaprincipal.setVisible(true);
        //VentanaTabla ventanatabla=new VentanaTabla();
        controladorPersona controladorpersona=new controladorPersona(ventanaprincipal);
        controladorDiurna controladordiurna=new controladorDiurna(ventanaprincipal);
        controladorConfiguracion controladorconfiguracion=new controladorConfiguracion(ventanaprincipal);
        controladorVespertina controladorvespertina=new controladorVespertina(ventanaprincipal);
        this.dispose();
       
    }//GEN-LAST:event_volverActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaIngreso().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JProgressBar barraprogreso;
    public javax.swing.JButton botondeingreso;
    public com.toedter.calendar.JCalendar calendario;
    public javax.swing.JComboBox cantidadatenciones;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JComboBox listacarrera;
    public javax.swing.JComboBox listaespecialidad;
    public javax.swing.JComboBox listafacultad;
    public javax.swing.JComboBox listaprofesional;
    public javax.swing.JComboBox listatipo;
    public javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
